### PR TITLE
fix error when the column is an integer

### PR DESCRIPTION
**Pull request by airwin**

### CODE REVIEW

**Comment by zippyui-react** [comment]
You should not change files in the /lib folder. Please make changes to the /src folder.
For development, just run `npm run dev` and navigate to localhost:9090 and you'll have a grid demo up and running.
Before sending a PR, make sure you run `npm run build`, which compiles the /src folder into the /lib folder (translates jsx into regular js)

**Comment by zippyui-react** [comment]
We appreciate your intention, but your PR does not solve a real problem. A column will never be an integer. It will generally be an object, or, it can be a string, the column name.

**Comment by airwin** [comment]
oh sorry I edit in the lib folder.
The problem I met is I have columns which name is an integer and then it throw an error in the `findColumn` function mentioned above. I will run dev & build to confirm it.

**Comment by zippyui-react** [comment]
Just convert the column name to a string:

```js
var columns = [{
   name: '1' //or number + ''
}]
```

**Pull request closed without merging**
