### PR TITLE
Fix groupBy bug preventing display of all data in grid

### PR DESCRIPTION
**Pull request by davertron**
Fix for issue #62

### CODE REVIEW

**Comment by radubrehar** [comment]
Good catch!

**Comment by davertron** [comment]
Thanks :)

Any idea when a new version will be published to npm? No rush, just curious.

**Comment by radubrehar** [comment]
hmmm..... good question...

**Comment by radubrehar** [comment]
try now :) version `1.2.14`

**Comment by davertron** [comment]
Awesome!!!

**Pull request merged**
