### PR TITLE
Feature style bem

### PR DESCRIPTION
**Pull request by bogdanpetru**
I found these calsses in style but not used in code:
- `z-wrapper` -> react-datagird__wrapper
- `z-summary` -> react-datagrid__summary
- `z-mask-wrapper` -> react-datagrid__mask-wrapper
- `z-loading` -> react-datagrid--loading 
- `z-content-wrapper-fix` -> react-datagrid__content-wrapper--fix
- `z-table-wrapper` -> react-datagrid__table-wrapper
- `menu-row` -> react-datagrid__header__menu__row
- `z-column-content` -> react-datagrid__column__content
- `z-columns-resizable` -> react-datagrid--columns-resizable

### CODE REVIEW

**Comment by bogdanpetru** [comment]
Classes only in tests:
z-align-right
z-text

**Comment by radubrehar** [comment]
Yes, there are some classes that are there and we don't use them for styling, but are very useful for users, they can target them to further style the component - for example the align classes - z-align-right/left

**Comment by bogdanpetru** [comment]
## React datagrid classes

- react-datagrid
  - react-datagrid--alternate
  - react-datagrid--ellipsis
  - react-datagrid--with-column-menu
  - react-datagrid--loading
  - react-datagrid--empty
  - react-datagrid--columns-resizable

##### loadmask
- react-datagrid__load_mask

##### load
- react-datagrid__mask-wrapper
- react-datagrid__mask-wrapper

##### containers
- react-datagrid__inner
- react-datagrid__wrapper

##### header
- react-datagrid__header
- react-datagrid__header-wrapper
  - react-datagrid__header-wrapper--dragging
- react-datagrid__header__menu__column
- react-datagrid__header__menu__row
  - react-datagrid__header__menu__row--over
- react-datagrid__header__button-show-menu
- react-datagrid__column-header
  - react-datagrid__column-header--filterable
  - react-datagrid__column-header--filtered
  - react-datagrid__column-header--active
  - react-datagrid__column-header--drag
  - react-datagrid__column-header--sortable
  - react-datagrid__column-header--over
  - react-datagrid__column-header--last
  - react-datagrid__column-header--first
- react-datagrid__column-header__filter
- react-datagrid__column-header__icon-sort-info
- react-datagrid__header_column__resize

##### footer
- react-datagrid__footer-wrapper

##### summary
- react-datagrid__summary

##### table
- react-datagrid__table
- react-datagrid__table-wrapper

##### row
- react-datagrid__row
  - react-datagrid__row--over
  - react-datagrid__row--odd
  - react-datagrid__row--selected

##### cell
- react-datagrid__cell
  - react-datagrid__cell--unselectable
  - react-datagrid__cell--first
  - react-datagrid__cell--asc
  - react-datagrid__cell--desc
  - react-datagrid__cell--drag
  - react-datagrid__cell--last

##### groups
- react-datagrid__group-row
- react-datagrid__group-cell

##### content
- react-datagrid__content
- react-datagrid__content-wrapper--fix

##### pagination
- react-datagrid__pagination-toolbar

##### empty text notice
- react-datagrid__empty-text

##### borders
- react-datagrid__borders--horizontal
- react-datagrid__borders--vertical

##### resize proxy
- react-datagrid__resize-proxy

**Comment by radubrehar** [comment]
The `react-datagrid--loading` class should be applied to the datagrid if the datasource is still loading/not resolved - for example when it is specified as a promise/function. As we will remove the support for `function` in dataSource, it will only need to be applied while the promise is not resolved yet.

**Comment by radubrehar** [comment]
Wow... good job! Looks great!

**Pull request closed without merging**
